# Generated by Django 4.2.3 on 2023-07-06 10:52

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('employeeID', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='ZA')),
                ('contractHours', models.DecimalField(decimal_places=2, max_digits=100)),
                ('profileImage', models.ImageField(height_field=400, upload_to='img/profiles/', width_field=400)),
                ('working_status', models.BooleanField(default=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='img/qr_codes/')),
            ],
        ),
    ]
