# Generated by Django 4.2.3 on 2023-07-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='profileImage',
            field=models.ImageField(upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes/'),
        ),
    ]
